#!/bin/bash
if [ `id -u` -eq 0 ];then
echo '开始安装。。。'
echo 'cp -r bin/* /usr/local/bin'
cp -r bin/* /usr/local/bin
echo 'cp -r share/qemu /usr/local/share'
cp -r share/* /usr/local/share
mkdir /usr/local/libexec
echo 'cp -r libexec/* /usr/local/libexec'
cp -r libexec/* /usr/local/libexec
cat uninstall >> /usr/local/bin/uninstall_qemu
chmod 755 /usr/local/bin/*
echo '安装完毕,如需卸载，执行uninstall_qemu'
else
echo "请确保你是以特权运行！"
fi
