name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure and compile
      run: ./build_compiler.sh
    - name: Upload arm64
      uses: actions/upload-artifact@v2
      with:
          name: qemu-compiler-arm64
          path: ./qemu-compiler-arm64.tar.gz
     - name: Upload x64
      uses: actions/upload-artifact@v2
      with:
          name: qemu-compiler-x64
          path: ./qemu-compiler-x64.tar.gz
        
